name: Chompy Nightly

on:
  push:  # Runs on every push to any branch
    branches:
      - '**'
  schedule:  # Runs nightly at 1 AM PST
    - cron: '0 9 * * *'  # 1 AM PST = 9 AM UTC

jobs:
  evaluation:
    runs-on: ubuntu-latest
    env:
      CHOMPY_EVALUATION_DIR: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive

      - name: Downgrade CMake
        run: |
          sudo apt-get remove --purge --auto-remove cmake
          sudo apt-get update
          sudo apt-get install -y wget
          wget -O cmake.tar.gz https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-linux-x86_64.tar.gz
          sudo tar -C /usr/local --strip-components=1 -xzf cmake.tar.gz
          cmake --version

      # should maybe get rid of this.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # - name: Install Flamegraph
      #   run: cargo install flamegraph

      - name: Generate Chompy Rules
        run: |
          cd chompy/
          cargo run --bin ruler -- handwritten "$CHOMPY_EVALUATION_DIR/chompy/chompy-rules.txt"

      # - name: Upload Flamegraph
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: flamegraph
      #     path: chompy/flamegraph.svg

      - name: Upload Chompy Rules
        uses: actions/upload-artifact@v4
        with:
          name: chompy-rules
          path: ${{ env.CHOMPY_EVALUATION_DIR }}/chompy/chompy-rules.txt

  caviar:
    runs-on: ubuntu-latest
    needs: evaluation
    env:
      CHOMPY_EVALUATION_DIR: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          submodules: false  # No need to pull submodules again

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Download Chompy Rules
        uses: actions/download-artifact@v4
        with:
          name: chompy-rules
          path: ${{ env.CHOMPY_EVALUATION_DIR }}

      - name: Run Caviar vs. Chompy comparison
        run: |
          cd "$CHOMPY_EVALUATION_DIR/eval"
          cargo run --release -- --eval-mode caviar \
            --dataset-path "$CHOMPY_EVALUATION_DIR/caviar/data/prefix/evaluation.csv" \
            --chompy-ruleset-path "$CHOMPY_EVALUATION_DIR/chompy-rules.txt" \
            --ruleset-comparison-output-path chompyvscaviar.json

      - name: Upload Caviar vs. Chompy results
        uses: actions/upload-artifact@v4
        with:
          name: eval
          path: ${{ env.CHOMPY_EVALUATION_DIR }}/eval/chompyvscaviar.json


  # @ninehusky -- Running this in CI is a bad idea. See #22.
  # eggsplanations:
  #   runs-on: ubuntu-20.04
  #   needs: evaluation
  #   env:
  #     CHOMPY_EVALUATION_DIR: ${{ github.workspace }}

  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: false  # No need to pull submodules again

  #     - name: Download Chompy Rules
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: chompy-rules
  #         path: ${{ env.CHOMPY_EVALUATION_DIR }}

  #     - name: Pull & update submodules recursively
  #       run: |
  #         git submodule update --init --recursive
  #         git submodule update --recursive --remote

  #     - name: Get eggsplanations
  #       run: |
  #         cd "$CHOMPY_EVALUATION_DIR/eval"
  #         cargo run --release -- --eval-mode eggsplain \
  #           --dataset-path "$CHOMPY_EVALUATION_DIR/caviar/data/prefix/evaluation.csv" \
  #           --chompy-ruleset-path "$CHOMPY_EVALUATION_DIR/chompy-rules.txt" \
  #           --explanation-output-path "$CHOMPY_EVALUATION_DIR/eval/eggsplain.json"

  #     - name: Upload eggsplanations
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: eggsplain
  #         path: ${{ env.CHOMPY_EVALUATION_DIR }}/eval/eggsplain.json

  derivability:
    runs-on: ubuntu-latest
    needs: evaluation
    env:
      CHOMPY_EVALUATION_DIR: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Download Chompy Rules
        uses: actions/download-artifact@v4
        with:
          name: chompy-rules
          path: ${{ env.CHOMPY_EVALUATION_DIR }}

      - name: Generate Caviar rules
        run: |
          cd "$CHOMPY_EVALUATION_DIR/python"
          python3 caviar_to_chompy.py --output "$CHOMPY_EVALUATION_DIR/chompy/caviar-rules.txt"

      - name: Perform derivability check
        run: |
          cd "$CHOMPY_EVALUATION_DIR/eval"
          cargo run --release -- --eval-mode derivability \
              --chompy-ruleset-path "$CHOMPY_EVALUATION_DIR/chompy-rules.txt" \
              --other-ruleset-path "$CHOMPY_EVALUATION_DIR/chompy/caviar-rules.txt" \
              --derivability-output-path "$CHOMPY_EVALUATION_DIR/derive-results.json"

      - name: Upload derivability check results
        uses: actions/upload-artifact@v4
        with:
          name: chompy-vs-caviar-derivability
          path: ${{ env.CHOMPY_EVALUATION_DIR }}/derive-results.json
