name: Chompy Nightly

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 9 * * *'  # 1 AM PST = 9 AM UTC

jobs:
  evaluation:
    runs-on: ubuntu-latest
    env:
      CHOMPY_EVALUATION_DIR: ${{ github.workspace }}
    strategy:
      matrix:
        args:
          - '--mode llm_alphabet_soup --output-path "${CHOMPY_EVALUATION_DIR}/chompy/chompy-rules.txt"'
          - '--mode handwritten --old-recipe-type og_recipe --output-path "${CHOMPY_EVALUATION_DIR}/chompy/chompy-rules.txt"'
          - '--mode handwritten --old-recipe-type og_recipe_no_conditions --output-path "${CHOMPY_EVALUATION_DIR}/chompy/chompy-rules.txt"'
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Pull & update submodules recursively
        run: git submodule update --init --recursive

      - name: Downgrade CMake
        run: |
          sudo apt-get remove --purge --auto-remove cmake
          sudo apt-get update
          sudo apt-get install -y wget
          wget -O cmake.tar.gz https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-linux-x86_64.tar.gz
          sudo tar -C /usr/local --strip-components=1 -xzf cmake.tar.gz
          cmake --version

      - name: Check Rust version
        run: rustc --version  # This will print the active Rust version

      - name: Install Flamegraph
        run: cargo install flamegraph

      - name: Generate Chompy Rules
        run: |
          cd chompy/
          cargo +stable build
          cargo +stable run --release -- ${{ matrix.args }}

      - name: Upload Flamegraph
        uses: actions/upload-artifact@v4
        with:
          name: flamegraph-${{ matrix.args }}
          path: chompy/flamegraph.svg

      - name: Upload Chompy Rules
        uses: actions/upload-artifact@v4
        with:
          name: chompy-rules-${{ matrix.args }}
          path: ${{ env.CHOMPY_EVALUATION_DIR }}/chompy/chompy-rules.txt

  caviar:
    needs: evaluation
    runs-on: ubuntu-latest
    env:
      CHOMPY_EVALUATION_DIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Pull & update submodules recursively
        run: git submodule update --init --recursive

      - name: Download Chompy Rules
        uses: actions/download-artifact@v4
        with:
          name: chompy-rules-${{ matrix.args }}
          path: ${{ env.CHOMPY_EVALUATION_DIR }}

      - name: Run Caviar vs. Chompy comparison
        run: |
          cd "$CHOMPY_EVALUATION_DIR/eval"
          cargo run --release -- --eval-mode caviar \
            --dataset-path "$CHOMPY_EVALUATION_DIR/caviar/data/prefix/evaluation.csv" \
            --chompy-ruleset-path "$CHOMPY_EVALUATION_DIR/chompy-rules.txt" \
            --ruleset-comparison-output-path chompyvscaviar.json

      - name: Upload Caviar vs. Chompy results
        uses: actions/upload-artifact@v4
        with:
          name: eval-${{ matrix.args }}
          path: ${{ env.CHOMPY_EVALUATION_DIR }}/eval/chompyvscaviar.json

      - name: Generate summary of results
        run: |
          cd "$CHOMPY_EVALUATION_DIR/python"
          python3 get_summary.py --filename "$CHOMPY_EVALUATION_DIR/eval/chompyvscaviar.json" > caviarsummary.txt

      - name: Upload Caviar vs. Chompy summary
        uses: actions/upload-artifact@v4
        with:
          name: eval-${{ matrix.args }}
          path: ${{ env.CHOMPY_EVALUATION_DIR }}/python/caviarsummary.txt

  derivability:
    needs: evaluation
    runs-on: ubuntu-latest
    env:
      CHOMPY_EVALUATION_DIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Pull & update submodules recursively
        run: git submodule update --init --recursive

      - name: Download Chompy Rules
        uses: actions/download-artifact@v4
        with:
          name: chompy-rules-${{ matrix.args }}
          path: ${{ env.CHOMPY_EVALUATION_DIR }}

      - name: Generate Caviar rules
        run: |
          cd "$CHOMPY_EVALUATION_DIR/python"
          python3 caviar_to_chompy.py --output "$CHOMPY_EVALUATION_DIR/chompy/caviar-rules.txt"

      - name: Perform derivability check
        run: |
          cd "$CHOMPY_EVALUATION_DIR/eval"
          cargo run --release -- --eval-mode derivability \
              --chompy-ruleset-path "$CHOMPY_EVALUATION_DIR/chompy-rules.txt" \
              --other-ruleset-path "$CHOMPY_EVALUATION_DIR/chompy/caviar-rules.txt" \
              --derivability-output-path "$CHOMPY_EVALUATION_DIR/derive-results.json"

      - name: Upload derivability check results
        uses: actions/upload-artifact@v4
        with:
          name: chompy-vs-caviar-derivability-${{ matrix.args }}
          path: ${{ env.CHOMPY_EVALUATION_DIR }}/derive-results.json
