name: Chompy Nightly

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "update"
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70
          default: true
          override: true
          components: rustfmt, clippy

      - name: Update Rust
        run: rustup update stable && rustup default stable

      - name: Generate Chompy rules
        run: |
          cd chompy/
          cargo build --release
          cargo test --test halide -- --nocapture
