name: Chompy Nightly

on:
  push:  # Runs on every push to any branch
    branches:
      - '**'
  schedule:  # Runs nightly at 1 AM PST
    - cron: '0 9 * * *'  # 1 AM PST = 9 AM UTC

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Flamegraph
        run: cargo install flamegraph

      - name: Generate Chompy Rules
        env:
          HALIDE_RULES_OUTPUT_PATH: chompy-rules.txt
        run: |
          cd chompy/
          cargo flamegraph --root --test halide -- --nocapture

      - name: Upload Flamegraph
        uses: actions/upload-artifact@v4
        with:
          name: flamegraph
          path: chompy/flamegraph.svg

      - name: Upload Chompy Rules
        uses: actions/upload-artifact@v4
        with:
          name: chompy-rules
          path: chompy/chompy-rules.txt

      - name: Run Caviar vs. Chompy comparison
        run: |
          cd eval/
          cargo run --release -- --eval-mode caviar --dataset-path ../../caviar/data/prefix/evaluation.csv --chompy-ruleset-path ../chompy/chompy-rules.txt --ruleset-comparison-output-path eval.json

      - name: Upload Caviar vs. Chompy results
        uses: actions/upload-artifact@v4
        with:
          name: eval
          path: eval/eval.json

      - name: Get eggsplanations
        run: |
          cd eval/
          cargo run --release -- --eval-mode eggsplain --dataset-path ../../caviar/data/prefix/evaluation.csv  --chompy-ruleset-path ../chompy/chompy-rules.txt --explanation-output-path ./eggsplain.json

      - name: Upload eggsplanations
        uses: actions/upload-artifact@v4
        with:
          name: eggsplain
          path: eval/eggsplain.json






