name: Chompy Nightly

on:
  push:  # Runs on every push to any branch
    branches:
      - '**'
  schedule:  # Runs nightly at 1 AM PST
    - cron: '0 9 * * *'  # 1 AM PST = 9 AM UTC

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Flamegraph
        run: cargo install flamegraph

      - name: Generate Chompy Rules
        run: |
          cd chompy/
          cargo flamegraph --root --test halide -- --nocapture

      - name: Upload Flamegraph
        uses: actions/upload-artifact@v4
        with:
          name: flamegraph
          path: chompy/flamegraph.svg
