name: Chompy Nightly

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 9 * * *'  # 1 AM PST = 9 AM UTC

jobs:
  caviar-internal:
    environment: eval
    runs-on: ubuntu-latest
    env:
      CHOMPY_EVALUATION_DIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          submodules: false  # No need to pull submodules again

      - name: Downgrade CMake
        run: |
          sudo apt-get remove --purge --auto-remove cmake
          sudo apt-get update
          sudo apt-get install -y wget
          wget -O cmake.tar.gz https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-linux-x86_64.tar.gz
          sudo tar -C /usr/local --strip-components=1 -xzf cmake.tar.gz
          cmake --version

      - name: Pull & update submodules recursively
        run: git submodule update --init --recursive

      - name: Run Caviar vs. Caviar (no cond) comparison
        run: |
          cd "$CHOMPY_EVALUATION_DIR/eval"
          cargo run --release -- --eval-mode caviar \
            --dataset-path "$CHOMPY_EVALUATION_DIR/caviar/data/prefix/evaluation.csv" \
            --ruleset-comparison-output-path chompyvscaviar.json

      - name: Upload Caviar vs. Chompy results
        uses: actions/upload-artifact@v4
        with:
          name: eval-caviar-no-cond-vs-caviar
          path: ${{ env.CHOMPY_EVALUATION_DIR }}/eval/chompyvscaviar.json

      - name: Generate summary of results
        run: |
          cd "$CHOMPY_EVALUATION_DIR/python"
          python3 get_summary.py --filename "$CHOMPY_EVALUATION_DIR/eval/chompyvscaviar.json" > caviarsummary.txt

      - name: Upload Caviar vs. Chompy summary
        uses: actions/upload-artifact@v4
        with:
          name: eval-caviar-no-cond-vs-caviar-summary
          path: ${{ env.CHOMPY_EVALUATION_DIR }}/python/caviarsummary.txt

  evaluation:
    environment: eval
    runs-on: ubuntu-latest
    env:
      CHOMPY_EVALUATION_DIR: ${{ github.workspace }}
    strategy:
      matrix:
        config:
          # - name: chatgpt
          #   args: '--mode llm_alphabet_soup'
          - name: handwritten_og_no_cond
            args: '--mode handwritten --old-recipe-type og_recipe_no_conditions'
          - name: handwritten_og
            args: '--mode handwritten --old-recipe-type og_recipe'

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive

      - name: Debug List all files in chompy
        run: ls -Rla chompy/

      - name: Downgrade CMake
        run: |
          sudo apt-get remove --purge --auto-remove cmake
          sudo apt-get update
          sudo apt-get install -y wget
          wget -O cmake.tar.gz https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-linux-x86_64.tar.gz
          sudo tar -C /usr/local --strip-components=1 -xzf cmake.tar.gz
          cmake --version

      - name: Downgrade CMake
        run: |
          sudo apt-get remove --purge --auto-remove cmake
          sudo apt-get update
          sudo apt-get install -y wget
          wget -O cmake.tar.gz https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-linux-x86_64.tar.gz
          sudo tar -C /usr/local --strip-components=1 -xzf cmake.tar.gz
          cmake --version

      - name: Check Rust version
        run: rustc --version  # This will print the active Rust version

      - name: Install Flamegraph
        run: cargo install flamegraph

      - name: Check API key length (safe)
        run: |
          echo "Key length: ${#OPENAI_API_KEY}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Generate Chompy Rules
        env:
           OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd chompy/
          cargo run --bin ruler -- handwritten "$CHOMPY_EVALUATION_DIR/chompy/chompy-rules.txt"

      - name: Upload Flamegraph
        uses: actions/upload-artifact@v4
        with:
          name: flamegraph-${{ matrix.config.args }}
          path: chompy/flamegraph.svg

      - name: Upload Chompy Rules
        uses: actions/upload-artifact@v4
        with:
          name: chompy-rules-${{ matrix.config.name }}
          path: ${{ env.CHOMPY_EVALUATION_DIR }}/chompy/chompy-rules.txt

  caviar:
    needs: evaluation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          # - name: chatgpt
          #   args: '--mode llm_alphabet_soup'
          - name: handwritten_og_no_cond
            args: '--mode handwritten --old-recipe-type og_recipe_no_conditions'
          - name: handwritten_og
            args: '--mode handwritten --old-recipe-type og_recipe'

    env:
      CHOMPY_EVALUATION_DIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          submodules: false  # No need to pull submodules again

      - name: Downgrade CMake
        run: |
          sudo apt-get remove --purge --auto-remove cmake
          sudo apt-get update
          sudo apt-get install -y wget
          wget -O cmake.tar.gz https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-linux-x86_64.tar.gz
          sudo tar -C /usr/local --strip-components=1 -xzf cmake.tar.gz
          cmake --version

      - name: Pull & update submodules recursively
        run: git submodule update --init --recursive

      - name: Download Chompy Rules
        uses: actions/download-artifact@v4
        with:
          name: chompy-rules-${{ matrix.config.name }}
          path: ${{ env.CHOMPY_EVALUATION_DIR }}

      - name: Run Caviar vs. Chompy comparison
        run: |
          cd "$CHOMPY_EVALUATION_DIR/eval"
          cargo run --release -- --eval-mode caviar \
            --dataset-path "$CHOMPY_EVALUATION_DIR/caviar/data/prefix/evaluation.csv" \
            --chompy-ruleset-path "$CHOMPY_EVALUATION_DIR/chompy-rules.txt" \
            --ruleset-comparison-output-path chompyvscaviar.json

      - name: Upload Caviar vs. Chompy results
        uses: actions/upload-artifact@v4
        with:
          name: eval-${{ matrix.config.name }}-vs-caviar
          path: ${{ env.CHOMPY_EVALUATION_DIR }}/eval/chompyvscaviar.json

      - name: Generate summary of results
        run: |
          cd "$CHOMPY_EVALUATION_DIR/python"
          python3 get_summary.py --filename "$CHOMPY_EVALUATION_DIR/eval/chompyvscaviar.json" > caviarsummary.txt

      - name: Upload Caviar vs. Chompy summary
        uses: actions/upload-artifact@v4
        with:
          name: eval-${{ matrix.config.name }}-summary
          path: ${{ env.CHOMPY_EVALUATION_DIR }}/python/caviarsummary.txt

  derivability:
    needs: evaluation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          # - name: chatgpt
          #   args: '--mode llm_alphabet_soup'
          - name: handwritten_og_no_cond
            args: '--mode handwritten --old-recipe-type og_recipe_no_conditions'
          - name: handwritten_og
            args: '--mode handwritten --old-recipe-type og_recipe'

    env:
      CHOMPY_EVALUATION_DIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Pull & update submodules recursively
        run: git submodule update --init --recursive

      - name: Downgrade CMake
        run: |
          sudo apt-get remove --purge --auto-remove cmake
          sudo apt-get update
          sudo apt-get install -y wget
          wget -O cmake.tar.gz https://github.com/Kitware/CMake/releases/download/v3.25.3/cmake-3.25.3-linux-x86_64.tar.gz
          sudo tar -C /usr/local --strip-components=1 -xzf cmake.tar.gz
          cmake --version

      - name: Download Chompy Rules
        uses: actions/download-artifact@v4
        with:
          name: chompy-rules-${{ matrix.config.name }}
          path: ${{ env.CHOMPY_EVALUATION_DIR }}

      - name: Generate Caviar rules
        run: |
          cd "$CHOMPY_EVALUATION_DIR/python"
          python3 caviar_to_chompy.py --output "$CHOMPY_EVALUATION_DIR/chompy/caviar-rules.txt"

      - name: Perform derivability check
        run: |
          cd "$CHOMPY_EVALUATION_DIR/eval"
          cargo run --release -- --eval-mode derivability \
              --chompy-ruleset-path "$CHOMPY_EVALUATION_DIR/chompy-rules.txt" \
              --other-ruleset-path "$CHOMPY_EVALUATION_DIR/chompy/caviar-rules.txt" \
              --derivability-output-path "$CHOMPY_EVALUATION_DIR/derive-results.json"

      - name: Upload derivability check results
        uses: actions/upload-artifact@v4
        with:
          name: chompy-vs-caviar-derivability-${{ matrix.config.args }}
          path: ${{ env.CHOMPY_EVALUATION_DIR }}/derive-results.json
